# Instructions for Google Cloud Build

steps:
  # 1. Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', 'deploy/Dockerfile', '-t', 'gcr.io/$PROJECT_ID/mount-of-mercy:$COMMIT_SHA', '.']

  # 2. Push the container image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/mount-of-mercy:$COMMIT_SHA']

  # 3. Deploy the container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'mount-of-mercy' # This is your service name
      - '--image'
      - 'gcr.io/$PROJECT_ID/mount-of-mercy:$COMMIT_SHA'
      - '--region'
      - 'us-west1' # The region you chose
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'

# Tell Cloud Build which images to save after the build
images:
  - 'gcr.io/$PROJECT_ID/mount-of-mercy:$COMMIT_SHA'

# Options block to specify where to store logs
options:
  logging: CLOUD_LOGGING_ONLY